name: Deploy website
on:
  push:
    branches:
      - develop

    pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          deploy-branch: master 
#          gatsby-args: --prefix-paths
          access-token: ${{ secrets.ACCESS_TOKEN }}
